### PR TITLE
[don't merge] Loading faces from memory: super slow?

### PR DESCRIPTION
**Pull request by lbud**

### CODE REVIEW

**Comment by springmeyer** [comment]
My results locally do not indicate a slowdown for `range`. I think the `load` is running so fast there is a lot of noise so take the differences with a grain of salt.

### overhaul
fontnik.load 1186 ops/sec 10 10
fontnik.range 22 ops/sec 1000 100

### overhaul-memory
fontnik.load 2825 ops/sec 10 10
fontnik.range 21 ops/sec 1000 100

**Comment by springmeyer** [comment]
bench2.js results:

### overhaul
fontnik.load x 509 ops/sec ±1.62% (45 runs sampled)
fontnik.range x 9.54 ops/sec ±1.82% (49 runs sampled)

### overhaul-memory
fontnik.load x 531 ops/sec ±1.46% (44 runs sampled)
fontnik.range x 9.44 ops/sec ±1.87% (49 runs sampled)

**Comment by springmeyer** [comment]
@lbud - just pushed a few minor improvements to this branch. To recap: I'm not seeing any slowdowns, so I think this is ready to merge if you can confirm the same. Interested to hear if you can still replicate slowdowns.

**Comment by lbud** [comment]
Aha, weird — ran both this morning and didn't see any slowdowns either once I reran `npm install --build-from-source`. I'm wondering if something about the way I had compiled it in debug mode before slowed it down, or if it was just from the million unresponsive atom helper process I had in the background on Friday (:unamused:). So, good to merge.

**Pull request merged**
