### PR TITLE
Add node8 binaries builds to travis

### PR DESCRIPTION
**Pull request by egoroof**
Fixes https://github.com/mapbox/node-fontnik/issues/138

### CODE REVIEW

**Comment by egoroof** [comment]
cc @springmeyer

**Comment by edpop** [comment]
Hello.
Any ETA for this?

**Comment by springmeyer** [comment]
Thanks for starting this. In addition to merging we'll need to publish binaries. Thinking we should hit other maintainence tasks at the same time, so I've proposed this being a part of https://github.com/mapbox/node-fontnik/issues/138.

**Comment by springmeyer** [comment]
landed in #144

**Pull request closed without merging**
