### PR TITLE
Port to node v12

### LINKED ISSUE #159: Cant install on 64bit Linux with node 12.7.0
Pre-built binaries for node 12.7.0 are not found, and it then fails to compiled on 64 bit linux. Compiler output as follow:

`  TOUCH Release/obj.target/action_before_build.stamp
  ACTION binding_gyp_action_before_build2_target_run_protoc_glyphs Release/obj/gen/glyphs.pb.cc
  TOUCH Release/obj.target/action_before_build2.stamp
  CXX(target) Release/obj.target/fontnik/src/node_fontnik.o
In file included from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_new.h:189:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:203,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)':
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to 'v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)'
                           , obj));
                                ^
In file included from /home/tom/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:4132:31: note: candidate: static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)
   static MaybeLocal<Function> New(
                               ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:4132:31: note:   no known conversion for argument 1 from 'v8::Isolate*' to 'v8::Local<v8::Context>'
In file included from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_new.h:189:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:203,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)':
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to 'v8::StringObject::New(v8::Local<v8::String>&)'
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/tom/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:5388:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:5388:23: note:   candidate expects 2 arguments, 1 provided
In file included from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_new.h:189:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:203,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before '>' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ')' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from ../src/glyphs.hpp:5:0,
                 from ../src/node_fontnik.cpp:2:
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:1034:53: error: no matching function for call to 'v8::Value::ToString()'
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /home/tom/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:2535:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:2535:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/tom/.node-gyp/12.7.0/include/node/v8-internal.h:14:0,
                 from /home/tom/.node-gyp/12.7.0/include/node/v8.h:25,
                 from /home/tom/.node-gyp/12.7.0/include/node/node.h:63,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:2550:3: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
   V8_DEPRECATED("Use maybe version",
   ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:2550:3: note:   candidate expects 1 argument, 0 provided
In file included from ../src/glyphs.hpp:5:0,
                 from ../src/node_fontnik.cpp:2:
/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:1044:74: error: no matching function for call to 'v8::String::WriteUtf8(char*&, int, int, const int&)'
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/tom/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:2745:7: note: candidate: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:2745:7: note:   no known conversion for argument 1 from 'char*' to 'v8::Isolate*'
../src/node_fontnik.cpp: In function 'void node_fontnik::RegisterModule(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/node_fontnik.cpp:8:102: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
     target->Set(Nan::New("load").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(Load)->GetFunction());
                                                                                                      ^
In file included from /home/tom/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:5955:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:5955:46: note:   candidate expects 1 argument, 0 provided
../src/node_fontnik.cpp:9:104: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
    target->Set(Nan::New("range").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(Range)->GetFunction());
                                                                                                       ^
In file included from /home/tom/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from /home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/node_modules/nan/nan.h:51,
                 from ../src/glyphs.hpp:5,
                 from ../src/node_fontnik.cpp:2:
/home/tom/.node-gyp/12.7.0/include/node/v8.h:5955:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^
/home/tom/.node-gyp/12.7.0/include/node/v8.h:5955:46: note:   candidate expects 1 argument, 0 provided
fontnik.target.mk:154: recipe for target 'Release/obj.target/fontnik/src/node_fontnik.o' failed
make: *** [Release/obj.target/fontnik/src/node_fontnik.o] Error 1
make: Leaving directory '/home/linuxbrew/.linuxbrew/lib/node_modules/fontnik/build'
`

### PR DESCRIPTION
**Pull request by springmeyer**
Based on top of #163, this adds Node v12 support.

Closes #159

/cc @mapbox/map-design-team @mapbox/static-apis @mapbox/maps-api

### CODE REVIEW

**Comment by jseppi** [comment]
@springmeyer Could the Node 12 support be done independently of the #163 work? I'm asking because it seems like #163 doesn't have a super clear path forward, while supporting Node 12 (and dropping EOL'd Node versions) seems narrowly-scoped enough to be done independently.

**Comment by springmeyer** [comment]
One consideration with #163 is that the composite functionality would be opt-in, since it is new functionality, meaning its lower risk. @jseppi we could however roll v12 support on it own, with extra work.

**Comment by springmeyer** [comment]
Update: Going to plan to work on node v12 soon that does not bundle any other potential breaking changes. So I'll revive and revisit this PR in the coming month or so.

**Comment by springmeyer** [comment]
> Going to plan to work on node v12 soon that does not bundle any other potential breaking changes.

Changed my mind. The changes in #163 really should not be breaking in any way. So, going to merge this into #163 and keep on working there.

**Pull request merged**
